### ISSUE TITLE
convert to epoc time

### ISSUE THREAD

**Issue by WestleyArgentum** [quinnj/Dates.jl#20]
Hey, sorry to bug you again. 

I started getting millisecond times like so:

``` julia
julia> int(Dates.now())
63544407604000
```

But they don't seem to be in epoc time (milliseconds since epoc? not sure how to say that exactly). I'm wondering what format they're in (do they count up from a different start date? or are they meant to be interpreted differently?) and whether there's an easy way to convert them (I need to use them with ICU.jl, which seems to expect milliseconds in epoc time)

**Comment by femtotrader** [comment]
I have found in doc
http://docs.julialang.org/en/release-0.4/stdlib/dates/
`datetime2unix` function
This is odd to return a Float64... why not just using integers to ensure exact resolution ?
(for milliseconds... but also for microsecond or less)
